In [1]:
import pandas as pd

In [10]:
#Intro to dataframes
df = pd.DataFrame([[1,2,3],[2,3,4],[4,6,7]],columns=['A','B','C'],index=['x','y','z'])

In [6]:
df.head()

   A  B  C
0  1  2  3
1  2  3  4
2  4  6  7

In [7]:
df.tail(2)

   A  B  C
1  2  3  4
2  4  6  7

In [12]:
df

   A  B  C
x  1  2  3
y  2  3  4
z  4  6  7

In [11]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [15]:
df.describe()

              A         B         C
count  3.000000  3.000000  3.000000
mean   2.333333  3.666667  4.666667
std    1.527525  2.081666  2.081666
min    1.000000  2.000000  3.000000
25%    1.500000  2.500000  3.500000
50%    2.000000  3.000000  4.000000
75%    3.000000  4.500000  5.500000
max    4.000000  6.000000  7.000000

In [16]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [18]:
df['A'].nunique

<bound method IndexOpsMixin.nunique of x    1
y    2
z    4
Name: A, dtype: int64>

In [20]:
df.shape

(3, 3)

In [21]:
df.size

9

Loading in Dataframes from files

In [3]:
coffee = pd.read_csv('D:/coffee.csv')

In [7]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [4]:
results = pd.read_parquet('D:/results.parquet')

In [10]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [11]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [12]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [13]:
coffee.tail(5)

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

In [15]:
coffee.sample(5)

         Day Coffee Type  Units Sold
7   Thursday       Latte          30
6   Thursday    Espresso          40
5  Wednesday       Latte          25
2    Tuesday    Espresso          30
4  Wednesday    Espresso          35

In [16]:
coffee.loc[#rows,#columns]

_IncompleteInputError: incomplete input (2089250730.py, line 1)

In [17]:
coffee.loc[0]

Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object

In [19]:
coffee.loc[5:]

          Day Coffee Type  Units Sold
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [21]:
coffee.loc[5:9,"Day"]

5    Wednesday
6     Thursday
7     Thursday
8       Friday
9       Friday
Name: Day, dtype: object

In [22]:
coffee.loc[5:8,["Day","Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [28]:
coffee.iloc[:, [0,2]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In [29]:
coffee.iloc[3:9,[0,1]]

         Day Coffee Type
3    Tuesday       Latte
4  Wednesday    Espresso
5  Wednesday       Latte
6   Thursday    Espresso
7   Thursday       Latte
8     Friday    Espresso

In [44]:
#coffee.index = coffee["Day"]

In [31]:
coffee.loc[0:5]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [32]:
coffee.head(
    
)

                 Day Coffee Type  Units Sold
Day
Monday        Monday    Espresso          25
Monday        Monday       Latte          15
Tuesday      Tuesday    Espresso          30
Tuesday      Tuesday       Latte          20
Wednesday  Wednesday    Espresso          35

In [33]:
coffee.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          15

In [34]:
coffee.loc["Monday":"Wednesday","Units Sold"]

Day
Monday       25
Monday       15
Tuesday      30
Tuesday      20
Wednesday    35
Wednesday    25
Name: Units Sold, dtype: int64

In [35]:
coffee.loc?

Type:        property
String form: <property object at 0x000002669489F650>
Docstring:
Access a group of rows and columns by label(s) or a boolean array.

``.loc[]`` is primarily label based, but may also be used with a
boolean array.

Allowed inputs are:

- A single label, e.g. ``5`` or ``'a'``, (note that ``5`` is
  interpreted as a *label* of the index, and **never** as an
  integer position along the index).
- A list or array of labels, e.g. ``['a', 'b', 'c']``.
- A slice object with labels, e.g. ``'a':'f'``.

  .. warning:: Note that contrary to usual python slices, **both** the
      start and the stop are included

- A boolean array of the same length as the axis being sliced,
  e.g. ``[True, False, True]``.
- An alignable boolean Series. The index of the key will be aligned before
  masking.
- An alignable Index. The Index of the returned selection will be the input.
- A ``callable`` function with one argument (the calling Series or
  DataFrame) and that returns valid output for indexing (one of the above)

See more at :ref:`Selection by Label <indexing.label>`.

Raises
------
KeyError
    If any items are not found.
IndexingError
    If an indexed key is passed and its index is unalignable to the frame index.

See Also
--------
DataFrame.at : Access a single value for a row/column label pair.
DataFrame.iloc : Access group of rows and columns by integer position(s).
DataFrame.xs : Returns a cross-section (row(s) or column(s)) from the
               Series/DataFrame.
Series.loc : Access group of values using labels.

Examples
--------
**Getting values**

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=['cobra', 'viper', 'sidewinder'],
...                   columns=['max_speed', 'shield'])
>>> df
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8

Single label. Note this returns the row as a Series.

>>> df.loc['viper']
max_speed    4
shield       5
Name: viper, dtype: int64

List of labels. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[['viper', 'sidewinder']]
            max_speed  shield
viper               4       5
sidewinder          7       8

Single label for row and column

>>> df.loc['cobra', 'shield']
2

Slice with labels for row and single label for column. As mentioned
above, note that both the start and stop of the slice are included.

>>> df.loc['cobra':'viper', 'max_speed']
cobra    1
viper    4
Name: max_speed, dtype: int64

Boolean list with the same length as the row axis

>>> df.loc[[False, False, True]]
            max_speed  shield
sidewinder          7       8

Alignable boolean Series:

>>> df.loc[pd.Series([False, True, False],
...                  index=['viper', 'sidewinder', 'cobra'])]
                     max_speed  shield
sidewinder          7       8

Index (same behavior as ``df.reindex``)

>>> df.loc[pd.Index(["cobra", "viper"], name="foo")]
       max_speed  shield
foo
cobra          1       2
viper          4       5

Conditional that returns a boolean Series

>>> df.loc[df['shield'] > 6]
            max_speed  shield
sidewinder          7       8

Conditional that returns a boolean Series with column labels specified

>>> df.loc[df['shield'] > 6, ['max_speed']]
            max_speed
sidewinder          7

Multiple conditional using ``&`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 1) & (df['shield'] < 8)]
            max_speed  shield
viper          4       5

Multiple conditional using ``|`` that returns a boolean Series

>>> df.loc[(df['max_speed'] > 4) | (df['shield'] < 5)]
            max_speed  shield
cobra               1       2
sidewinder          7       8

Please ensure that each condition is wrapped in parentheses ``()``.
See the :ref:`user guide<indexing.boolean>`
for more details and explanations of Boolean indexing.

.. note::
    If you find yourself using 3 or more conditionals in ``.loc[]``,
    consider using :ref:`advanced indexing<advanced.advanced_hierarchical>`.

    See below for using ``.loc[]`` on MultiIndex DataFrames.

Callable that returns a boolean Series

>>> df.loc[lambda df: df['shield'] == 8]
            max_speed  shield
sidewinder          7       8

**Setting values**

Set value for all items matching the list of labels

>>> df.loc[['viper', 'sidewinder'], ['shield']] = 50
>>> df
            max_speed  shield
cobra               1       2
viper               4      50
sidewinder          7      50

Set value for an entire row

>>> df.loc['cobra'] = 10
>>> df
            max_speed  shield
cobra              10      10
viper               4      50
sidewinder          7      50

Set value for an entire column

>>> df.loc[:, 'max_speed'] = 30
>>> df
            max_speed  shield
cobra              30      10
viper              30      50
sidewinder         30      50

Set value for rows matching callable condition

>>> df.loc[df['shield'] > 35] = 0
>>> df
            max_speed  shield
cobra              30      10
viper               0       0
sidewinder          0       0

Add value matching location

>>> df.loc["viper", "shield"] += 5
>>> df
            max_speed  shield
cobra              30      10
viper               0       5
sidewinder          0       0

Setting using a ``Series`` or a ``DataFrame`` sets the values matching the
index labels, not the index positions.

>>> shuffled_df = df.loc[["viper", "cobra", "sidewinder"]]
>>> df.loc[:] += shuffled_df
>>> df
            max_speed  shield
cobra              60      20
viper               0      10
sidewinder          0       0

**Getting values on a DataFrame with an index that has integer labels**

Another example using integers for the index

>>> df = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
...                   index=[7, 8, 9], columns=['max_speed', 'shield'])
>>> df
   max_speed  shield
7          1       2
8          4       5
9          7       8

Slice with integer labels for rows. As mentioned above, note that both
the start and stop of the slice are included.

>>> df.loc[7:9]
   max_speed  shield
7          1       2
8          4       5
9          7       8

**Getting values with a MultiIndex**

A number of examples using a DataFrame with a MultiIndex

>>> tuples = [
...     ('cobra', 'mark i'), ('cobra', 'mark ii'),
...     ('sidewinder', 'mark i'), ('sidewinder', 'mark ii'),
...     ('viper', 'mark ii'), ('viper', 'mark iii')
... ]
>>> index = pd.MultiIndex.from_tuples(tuples)
>>> values = [[12, 2], [0, 4], [10, 20],
...           [1, 4], [7, 1], [16, 36]]
>>> df = pd.DataFrame(values, columns=['max_speed', 'shield'], index=index)
>>> df
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Single label. Note this returns a DataFrame with a single index.

>>> df.loc['cobra']
         max_speed  shield
mark i          12       2
mark ii          0       4

Single index tuple. Note this returns a Series.

>>> df.loc[('cobra', 'mark ii')]
max_speed    0
shield       4
Name: (cobra, mark ii), dtype: int64

Single label for row and column. Similar to passing in a tuple, this
returns a Series.

>>> df.loc['cobra', 'mark i']
max_speed    12
shield        2
Name: (cobra, mark i), dtype: int64

Single tuple. Note using ``[[]]`` returns a DataFrame.

>>> df.loc[[('cobra', 'mark ii')]]
               max_speed  shield
cobra mark ii          0       4

Single tuple for the index with a single label for the column

>>> df.loc[('cobra', 'mark i'), 'shield']
2

Slice from index tuple to single label

>>> df.loc[('cobra', 'mark i'):'viper']
                     max_speed  shield
cobra      mark i           12       2
           mark ii           0       4
sidewinder mark i           10      20
           mark ii           1       4
viper      mark ii           7       1
           mark iii         16      36

Slice from index tuple to index tuple

>>> df.loc[('cobra', 'mark i'):('viper', 'mark ii')]
                    max_speed  shield
cobra      mark i          12       2
           mark ii          0       4
sidewinder mark i          10      20
           mark ii          1       4
viper      mark ii          7       1

Please see the :ref:`user guide<advanced.advanced_hierarchical>`
for more details and explanations of advanced indexing.

In [53]:
coffee.reset_index(drop=True,inplace= True)

In [55]:
coffee.loc[1,"Units Sold"]= 10

In [56]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        25.0
1      Monday       Latte        10.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0
14        NaN         NaN        10.0

In [57]:
coffee.loc[0:3,"Units Sold"] = 14

In [59]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso        14.0
1      Monday       Latte        14.0
2     Tuesday    Espresso        14.0
3     Tuesday       Latte        14.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0
14        NaN         NaN        10.0

In [61]:
coffee.at[5,"Units Sold"]

np.float64(25.0)

In [4]:
coffee["Day"]

0        Monday
1        Monday
2       Tuesday
3       Tuesday
4     Wednesday
5     Wednesday
6      Thursday
7      Thursday
8        Friday
9        Friday
10     Saturday
11     Saturday
12       Sunday
13       Sunday
Name: Day, dtype: object

In [6]:
coffee.sort_values("Units Sold")

          Day Coffee Type  Units Sold
1      Monday       Latte          15
3     Tuesday       Latte          20
0      Monday    Espresso          25
5   Wednesday       Latte          25
2     Tuesday    Espresso          30
7    Thursday       Latte          30
4   Wednesday    Espresso          35
9      Friday       Latte          35
13     Sunday       Latte          35
11   Saturday       Latte          35
6    Thursday    Espresso          40
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45

In [7]:
coffee.sort_values("Units Sold",ascending=False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [9]:
coffee.sort_values(["Units Sold","Coffee Type"],ascending=[0,1])

          Day Coffee Type  Units Sold
8      Friday    Espresso          45
10   Saturday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
9      Friday       Latte          35
11   Saturday       Latte          35
13     Sunday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

In [10]:
for index,row in coffee.iterrows():
    print(index)
    print(row)
    print("\n\n\n")

0
Day              Monday
Coffee Type    Espresso
Units Sold           25
Name: 0, dtype: object




1
Day            Monday
Coffee Type     Latte
Units Sold         15
Name: 1, dtype: object




2
Day             Tuesday
Coffee Type    Espresso
Units Sold           30
Name: 2, dtype: object




3
Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object




4
Day            Wednesday
Coffee Type     Espresso
Units Sold            35
Name: 4, dtype: object




5
Day            Wednesday
Coffee Type        Latte
Units Sold            25
Name: 5, dtype: object




6
Day            Thursday
Coffee Type    Espresso
Units Sold           40
Name: 6, dtype: object




7
Day            Thursday
Coffee Type       Latte
Units Sold           30
Name: 7, dtype: object




8
Day              Friday
Coffee Type    Espresso
Units Sold           45
Name: 8, dtype: object




9
Day            Friday
Coffee Type     Latte
Units Sold         35
Name: 9, dtype: object




10
Day            Saturday
Coffee Type    Espresso
Units Sold           45
Name: 10, dtype: object




11
Day            Saturday
Coffee Type       Latte
Units Sold           35
Name: 11, dtype: object




12
Day              Sunday
Coffee Type    Espresso
Units Sold           45
Name: 12, dtype: object




13
Day            Sunday
Coffee Type     Latte
Units Sold         35
Name: 13, dtype: object

In [12]:
for index,row in coffee.iterrows():
    print(index)
    print(row['Units Sold'])
    print("\n\n")

0
25



1
15



2
30



3
20



4
35



5
25



6
40



7
30



8
45



9
35



10
45



11
35



12
45



13
35

Filtering data

In [14]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [15]:
results.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308408 entries, 0 to 308407
Data columns (total 11 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   year        305807 non-null  float64
 1   type        305807 non-null  object
 2   discipline  308407 non-null  object
 3   event       308408 non-null  object
 4   as          308408 non-null  object
 5   athlete_id  308408 non-null  int64
 6   noc         308407 non-null  object
 7   team        121714 non-null  object
 8   place       283193 non-null  float64
 9   tied        308408 non-null  bool
 10  medal       44139 non-null   object
dtypes: bool(1), float64(2), int64(1), object(7)
memory usage: 23.8+ MB

In [2]:
import pandas as pd
import numpy as np
bios = pd.read_csv("D:/bios.csv")

In [17]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [19]:
bios.loc[bios['height_cm']>215,['name','height_cm']]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

In [23]:
bios.loc[bios['height_cm']>215][['name','born_city','height_cm']]

                         name               born_city  height_cm
5089       Viktor Pankrashkin         Moskva (Moscow)      220.0
5583     Paulinho Villas Boas               São Paulo      217.0
5673           Gunther Behnke              Leverkusen      221.0
5716                 Uwe Blab        München (Munich)      218.0
5781           Tommy Burleson               Crossnore      223.0
5796            Andy Campbell               Melbourne      218.0
6223              Lars Hansen  København (Copenhagen)      216.0
6270              Hu Zhangbao                     NaN      216.0
6409         Sergey Kovalenko                     NaN      216.0
6420            Jānis Krūmiņš                   Cēsis      218.0
6504              Luc Longley               Melbourne      220.0
6722         Shaquille O'Neal                  Newark      216.0
6937           David Robinson                Key West      216.0
6978          Arvydas Sabonis                  Kaunas      223.0
7074           Paulo da Silva               São Paulo      217.0
7188       Vladimir Tkachenko               Golovinka      220.0
7281         Stojko Vranković                   Drniš      217.0
7376      Eurelijus Žukauskas                Klaipėda      218.0
52608         Aleksey Kazakov      Naberezhnye Chelny      217.0
82100           Frédéric Weis              Thionville      218.0
89070                Yao Ming          Xuhui District      226.0
89075          Roberto Dueñas                  Madrid      221.0
107408       Peter John Ramos                 Fajardo      219.0
112312           Stanko Barać                  Mostar      217.0
112332    Andreas Glyniadakis                  Chania      216.0
112337          Hamed Haddadi                   Ahvaz      218.0
118663         Timofey Mozgov                     NaN      216.0
118676        Dmitry Musersky                Makiïvka      219.0
120266           Zhang Zhaoxu                 Binzhou      221.0
121694            Salah Mejri                Jendouba      216.0
123850         Tyson Chandler                 Hanford      216.0
130460               Li Muhao                 Guiyang      218.0
130461                Zhou Qi                Xinxiang      217.0
138671          Ondřej Balvín          Ústí nad Labem      216.0
139365         Moustapha Fall                   Paris      218.0

In [24]:
bios.loc[(bios['height_cm']>215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [25]:
bios[bios['name'].str.contains("Keith")]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [26]:
bios[bios['name'].str.contains("keith",case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [27]:
bios[bios['name'].str.contains("keith")]

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [28]:
bios[bios['name'].str.contains("Keith|patrick",case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [ ]:
bios[bios['name'].str.contains("Keith|patrick",case=False,regex=False)] 
# no name is here like keith patrick

Empty DataFrame
Columns: [athlete_id, name, born_date, born_city, born_region, born_country, NOC, height_cm, weight_kg, died_date]
Index: []

In [30]:
bios[bios['born_country'].isin(["USA","FRA","GBR"])]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145454,149180,Anna Hoffmann,2000-03-28,Madison,Wisconsin,USA,United States,NaN,NaN,NaN
145457,149183,Alix Wilkinson,2000-08-02,Mammoth Lakes,California,USA,United States,NaN,NaN,NaN
145467,149194,Elisa Nakab,1998-05-08,Briançon,Hautes-Alpes,FRA,Italy,NaN,NaN,NaN
145468,149195,Justin Abdelkader,1987-02-25,Muskegon,Michigan,USA,United States,187.0,97.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18

In [31]:
bios[bios['born_country'].isin(["USA","FRA","GBR"]) & (bios['name'].str.startswith("Keith"))]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
14577,14674,Keith Harrison,1933-03-28,Birmingham,England,GBR,Great Britain,NaN,NaN,NaN
16166,16281,Keith Reynolds,1963-12-25,Solihull,England,GBR,Great Britain,173.0,68.0,NaN
18734,18862,Keith Sinclair,1945-06-26,Sunderland,England,GBR,Great Britain,190.0,79.0,NaN
29897,30123,Keith Langley,1961-06-03,Aldershot,England,GBR,Great Britain,173.0,70.0,NaN
34011,34275,Keith Remfry,1947-11-17,Ealing,England,GBR,Great Britain,193.0,114.0,2015-09-16
46885,47234,Keith Collin,1937-01-18,Marylebone,England,GBR,Great Britain,168.0,63.0,1991-03-06
50929,51288,Keith Carter,1924-08-30,Akron,Ohio,USA,United States,NaN,NaN,2013-05-03
51185,51544,Keith Russell,1948-01-15,Mesa,Arizona,USA,United States,188.0,73.0,NaN
52913,53288,Keith Erickson,1944-04-19,San Francisco,California,USA,United States,196.0,86.0,NaN
55317,55712,Keith Boxell,1958-05-06,Clapham,England,GBR,Great Britain,170.0,87.0,NaN
57818,58226,Keith Peache,1947-08-10,Lewisham,England,GBR,Great Britain,180.0,98.0,NaN
61748,62202,Keith Grogono,1912-11-04,Stratford,England,GBR,Great Britain,NaN,NaN,1999-03-22
62620,63086,Keith Musto,1936-01-12,Rochford,England,GBR,Great Britain,174.0,72.0,NaN
62678,63144,Keith Notary,1960-01-22,Merritt Island,Florida,USA,United States,170.0,66.0,NaN
68324,68841,Keith Angus,1943-04-05,Sheffield,England,GBR,Great Britain,170.0,59.0,NaN
68472,68989,Keith Cullen,1972-06-13,Ilford,England,GBR,Great Britain,177.0,61.0,NaN
68997,69514,Keith Stock,1957-03-18,Woolwich,England,GBR,Great Britain,176.0,73.0,NaN
77550,78141,Keith Brantly,1962-05-23,Scott Air Force Base,Illinois,USA,United States,180.0,64.0,NaN
84097,84766,Keith Christiansen,1944-07-14,International Falls,Minnesota,USA,United States,165.0,69.0,2018-11-05
94646,95413,Keith Meyer,1938-06-20,Geneva,Illinois,USA,United States,NaN,NaN,2010-07-25
95267,96037,Keith Oliver,1947-10-27,Liverpool,England,GBR,Great Britain,172.0,68.0,NaN
96452,97229,Keith Schellenberg,1929-03-13,Middlesbrough,England,GBR,Great Britain,NaN,NaN,2019-10-28
97499,98286,Keith Tkachuk,1972-03-28,Melrose,Massachusetts,USA,United States,188.0,102.0,NaN
98068,98860,Keith Wegeman,1929-08-28,Denver,Colorado,USA,United States,NaN,NaN,1974-08-22
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN

In [33]:
bios.query('born_country == "USA" and born_city== ["California","Washington"]')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
2772,2784,Pete Sampras,1971-08-12,Washington,District of Columbia,USA,United States,185.0,79.0,NaN
5344,5363,Katrina McClain,1965-09-19,Washington,District of Columbia,USA,United States,188.0,62.0,NaN
5386,5405,Cindy Noble,1958-11-14,Washington,Ohio,USA,United States,195.0,75.0,NaN
5810,5833,Kenny Carr,1955-08-15,Washington,District of Columbia,USA,United States,200.0,102.0,NaN
5898,5923,Perry Crosswhite,1947-09-22,Washington,District of Columbia,USA,Australia,206.0,92.0,NaN
...,...,...,...,...,...,...,...,...,...,...
133348,136287,Gary Russell,1996-06-14,Washington,District of Columbia,USA,United States,173.0,64.0,NaN
135178,138322,Haley Skarupa,1994-01-03,Washington,District of Columbia,USA,United States,168.0,64.0,NaN
143628,147281,Phoebe Bacon,2002-08-12,Washington,District of Columbia,USA,United States,178.0,NaN,NaN
143721,147376,Troy Isley,1998-09-05,Washington,District of Columbia,USA,United States,178.0,NaN,NaN
143830,147486,Morgan Pearson,1993-09-22,Washington,District of Columbia,USA,United States,181.0,NaN,NaN

In [1]:
import numpy as np 
import pandas as pd

In [3]:
coffee = pd.read_csv('D:/coffee.csv')
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

Adding/ Removing Coloumnd

In [67]:
coffee.head(
    
)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [68]:
coffee['price']=4.99

In [69]:
coffee.head()

         Day Coffee Type  Units Sold  price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [40]:
coffee['new_price']=np.where(coffee['Coffee Type']=='Espresso',3.99,5.99)

In [71]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [72]:
coffee.drop(columns=['price'])

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [73]:
coffee.drop(0)

          Day Coffee Type  Units Sold  price  new_price
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [49]:
coffee.drop(columns=['price'],inplace=True)

In [74]:
coffee

          Day Coffee Type  Units Sold  price  new_price
0      Monday    Espresso          25   4.99       3.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       3.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       3.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       3.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       3.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       3.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       3.99
13     Sunday       Latte          35   4.99       5.99

In [51]:
coffee_new = coffee.copy()
coffee_new['price']=4.99

In [54]:
coffee_new

          Day Coffee Type  Units Sold  new_price  price
0      Monday    Espresso          25       3.99   4.99
1      Monday       Latte          15       5.99   4.99
2     Tuesday    Espresso          30       3.99   4.99
3     Tuesday       Latte          20       5.99   4.99
4   Wednesday    Espresso          35       3.99   4.99
5   Wednesday       Latte          25       5.99   4.99
6    Thursday    Espresso          40       3.99   4.99
7    Thursday       Latte          30       5.99   4.99
8      Friday    Espresso          45       3.99   4.99
9      Friday       Latte          35       5.99   4.99
10   Saturday    Espresso          45       3.99   4.99
11   Saturday       Latte          35       5.99   4.99
12     Sunday    Espresso          45       3.99   4.99
13     Sunday       Latte          35       5.99   4.99

In [53]:
coffee.drop(columns=['price'],inplace=True)

KeyError: "['price'] not found in axis"

In [55]:
coffee

          Day Coffee Type  Units Sold  new_price
0      Monday    Espresso          25       3.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       3.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       3.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       3.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       3.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       3.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       3.99
13     Sunday       Latte          35       5.99

In [41]:
coffee=pd.read_csv('D:/coffee.csv')

In [75]:
coffee['revenue']=coffee['Units Sold']*coffee['new_price']

In [79]:
coffee.head()

         Day Coffee Type  Units Sold  price  price  revenue
0     Monday    Espresso          25   4.99   3.99    99.75
1     Monday       Latte          15   4.99   5.99    89.85
2    Tuesday    Espresso          30   4.99   3.99   119.70
3    Tuesday       Latte          20   4.99   5.99   119.80
4  Wednesday    Espresso          35   4.99   3.99   139.65

In [77]:
coffee = coffee.rename(columns={'new_price':'price'})

In [78]:
coffee.head()

         Day Coffee Type  Units Sold  price  price  revenue
0     Monday    Espresso          25   4.99   3.99    99.75
1     Monday       Latte          15   4.99   5.99    89.85
2    Tuesday    Espresso          30   4.99   3.99   119.70
3    Tuesday       Latte          20   4.99   5.99   119.80
4  Wednesday    Espresso          35   4.99   3.99   139.65

In [ ]:
coffee = coffee.drop(columns=)

In [81]:
bios = pd.read_csv('D:/bios.csv')

In [82]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [4]:
bios_new= bios.copy()

In [86]:
bios_new['first_name']= bios_new['name'].str.split(' ').str[0]

In [87]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [88]:
bios_new.query('first_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

In [5]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [6]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,1913-07-15

In [93]:
bios_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   athlete_id     145500 non-null  int64
 1   name           145500 non-null  object
 2   born_date      143693 non-null  datetime64[ns]
 3   born_city      110908 non-null  object
 4   born_region    110908 non-null  object
 5   born_country   110908 non-null  object
 6   NOC            145499 non-null  object
 7   height_cm      106651 non-null  float64
 8   weight_kg      102070 non-null  float64
 9   died_date      33940 non-null   object
 10  first_name     145500 non-null  object
 11  born_datetime  143693 non-null  datetime64[ns]
dtypes: datetime64[ns](2), float64(2), int64(1), object(7)
memory usage: 13.3+ MB

In [95]:
bios_new['born_year']= bios_new['born_datetime'].dt.year
bios_new[['name','born_year']]

                         name  born_year
0       Jean-François Blanchy     1886.0
1              Arnaud Boetsch     1969.0
2                Jean Borotra     1898.0
3             Jacques Brugnon     1895.0
4                Albert Canet     1878.0
...                       ...        ...
145495      Polina Luchnikova     2002.0
145496    Valeriya Merkusheva     1999.0
145497        Yuliya Smirnova     1998.0
145498         André Foussard     1899.0
145499          Bill Phillips     1913.0

[145500 rows x 2 columns]

In [104]:
bios_new['datetime'] = pd.to_datetime(bios_new['born_datetime'],format="%d-%m-%Y")

In [105]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,first_name,born_datetime,born_year,datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François,1886-12-12,1886.0,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud,1969-04-01,1969.0,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean,1898-08-13,1898.0,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques,1895-05-11,1895.0,1895-05-11
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert,1878-04-17,1878.0,1878-04-17
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina,2002-01-30,2002.0,2002-01-30
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya,1999-09-20,1999.0,1999-09-20
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya,1998-05-08,1998.0,1998-05-08
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André,1899-05-19,1899.0,1899-05-19
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill,1913-07-15,1913.0,1913-07-15

In [107]:
bios_new.to_csv('D:/bios_new.csv',index=False)

In [2]:
import pandas as pd
bios = pd.read_csv('D:/bios.csv')

In [3]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20

In [4]:
bios['height_category']= bios['height_cm'].apply(lambda x:'Short' if x<165 else('Average' if x<185 else 'Tall'))

In [5]:
bios

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Average
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Average
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Short
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,Average
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Tall

In [8]:
def categorize_athlete(row):
    if row['height_cm'] <1775 and row['weight_kg']<70:
        return 'Loghtweght'
    elif row['height_cm']<185 and row['weight_kg']<=80:
        return 'Middleweight'
    else:
        return 'Heavyweight'
bios['Category']=bios.apply(categorize_athlete,axis=1)

In [9]:
bios.head(9)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,height_category,Category
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Tall,Heavyweight
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Average,Middleweight
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Average,Middleweight
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Average,Loghtweght
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Tall,Heavyweight
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN,Average,Middleweight
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN,Average,Middleweight
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02,Tall,Heavyweight
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01,Tall,Heavyweight

Merging & Concatenating Data

In [1]:
import pandas as pd
nocs = pd.read_csv('D:/noc_regions.csv')

In [2]:
nocs.head()

   NOC       region                 notes
0  AFG  Afghanistan                   NaN
1  AHO      Curacao  Netherlands Antilles
2  ALB      Albania                   NaN
3  ALG      Algeria                   NaN
4  AND      Andorra                   NaN

In [7]:
bios = pd.read_csv('D:/bios.csv')

In [7]:
bios.head(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
5,6,Nicolas Chatelain,1970-01-13,Amiens,Somme,FRA,France,181.0,70.0,NaN
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
7,8,Henri Cochet,1901-12-14,Villeurbanne,Rhône,FRA,France,NaN,NaN,1987-04-02
8,9,Marcel Cousin,1896-08-04,Nîmes,Gard,FRA,France,NaN,NaN,1986-08-01
9,10,Guy de la Chapelle,1868-07-16,Farges-Allichamps,Cher,FRA,France,NaN,NaN,1923-08-27

In [5]:
bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')

In [6]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN

In [8]:
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [9]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,born_country_full,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [10]:
bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left',suffixes=["bios","nocs"])

In [11]:
bios_new.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOCbios,height_cm,weight_kg,died_date,NOCnocs,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN

In [12]:
bios_new=pd.merge(bios,nocs,left_on='born_country',right_on='NOC',how='left')

In [13]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC_x,height_cm,weight_kg,died_date,NOC_y,region,notes
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,FRA,France,NaN
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,FRA,France,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,FRA,France,NaN
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,FRA,France,NaN
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,GBR,UK,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,RUS,Russia,NaN
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,RUS,Russia,NaN
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,RUS,Russia,NaN
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,FRA,France,NaN
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,AUS,Australia,NaN

In [14]:
bios_new.rename(columns={'region':'born_country_full'},inplace=True)

In [16]:
bios_new[bios_new['NOC_x'] != bios_new['born_country_full']][['name','NOC_x','born_country_full']]

                       name    NOC_x born_country_full
4              Albert Canet   France                UK
12                J. Defert   France               NaN
13           Étienne Durand   France               NaN
16               Guy Forget   France           Morocco
27       Guy, Baron Lejeune   France               NaN
...                     ...      ...               ...
145491        Matthew Wepke  Jamaica               NaN
145493   Landysh Falyakhova      ROC            Russia
145495    Polina Luchnikova      ROC            Russia
145496  Valeriya Merkusheva      ROC            Russia
145497      Yuliya Smirnova      ROC            Russia

[73210 rows x 3 columns]

In [19]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()

In [20]:
usa.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [21]:
gbr.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25
37,38,Helen Aitchison,1881-12-06,Sunderland,England,GBR,Great Britain,NaN,NaN,1947-05-26
38,39,Geraldine Beamish,1883-06-23,Forest Gate,England,GBR,Great Britain,NaN,NaN,1972-05-10
39,40,Dora Boothby,1881-08-02,Finchley,England,GBR,Great Britain,NaN,NaN,1970-02-22
40,41,Julie Bradbury,1967-02-12,Oxford,England,GBR,Great Britain,175.0,64.0,NaN

In [22]:
new_df = pd.concat([usa,gbr])

In [25]:
new_df.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
54,55,Monique Javer,1967-07-22,Burlingame,California,USA,Great Britain,177.0,64.0,NaN
960,964,Xóchitl Escobedo,1968-09-17,West Covina,California,USA,Mexico,170.0,60.0,NaN
961,965,Angélica Gavaldón,1973-10-03,El Centro,California,USA,Mexico,160.0,54.0,NaN
1231,1238,Bert Schneider,1897-07-01,Cleveland,Ohio,USA,Canada,NaN,NaN,1986-02-20
1345,1352,Laura Berg,1975-01-06,Santa Fe Springs,California,USA,United States,168.0,61.0,NaN

In [5]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None

In [8]:
combine_df = pd.merge(results,bios,on='athlete_id',how='left')

In [9]:
combine_df.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,17.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,None,32.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,None,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02

Handling Null Valuess

In [2]:

import pandas as pd
coffee = pd.read_csv('D:/coffee.csv')

In [13]:
import numpy as np
coffee.loc[[0,1],'Units Sold']=np.nan

In [14]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso         NaN
1     Monday       Latte         NaN
2    Tuesday    Espresso        30.0
3    Tuesday       Latte        20.0
4  Wednesday    Espresso        35.0

In [15]:
coffee.isna().sum()

Day            0
Coffee Type    0
Units Sold     2
dtype: int64

In [17]:
coffee.fillna(coffee['Units Sold'].mean())

          Day Coffee Type  Units Sold
0      Monday    Espresso        35.0
1      Monday       Latte        35.0
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [ ]:
import numpy as np

In [14]:
coffee.loc[[0,1],'Units Sold'] = np.nan
coffee

          Day Coffee Type  Units Sold  Unitss Sold
0      Monday    Espresso         NaN          NaN
1      Monday       Latte         NaN          NaN
2     Tuesday    Espresso        30.0          NaN
3     Tuesday       Latte        20.0          NaN
4   Wednesday    Espresso        35.0          NaN
5   Wednesday       Latte        25.0          NaN
6    Thursday    Espresso        40.0          NaN
7    Thursday       Latte        30.0          NaN
8      Friday    Espresso        45.0          NaN
9      Friday       Latte        35.0          NaN
10   Saturday    Espresso        45.0          NaN
11   Saturday       Latte        35.0          NaN
12     Sunday    Espresso        45.0          NaN
13     Sunday       Latte        35.0          NaN

In [19]:
coffee.fillna(coffee['Units Sold'].mean())
coffee

          Day Coffee Type  Units Sold  Unitss Sold
0      Monday    Espresso         NaN          NaN
1      Monday       Latte         NaN          NaN
2     Tuesday    Espresso        30.0          NaN
3     Tuesday       Latte        20.0          NaN
4   Wednesday    Espresso        35.0          NaN
5   Wednesday       Latte        25.0          NaN
6    Thursday    Espresso        40.0          NaN
7    Thursday       Latte        30.0          NaN
8      Friday    Espresso        45.0          NaN
9      Friday       Latte        35.0          NaN
10   Saturday    Espresso        45.0          NaN
11   Saturday       Latte        35.0          NaN
12     Sunday    Espresso        45.0          NaN
13     Sunday       Latte        35.0          NaN

In [20]:
coffee['Units Sold']=coffee['Units Sold'].interpolate()

In [21]:
coffee

          Day Coffee Type  Units Sold  Unitss Sold
0      Monday    Espresso         NaN          NaN
1      Monday       Latte         NaN          NaN
2     Tuesday    Espresso        30.0          NaN
3     Tuesday       Latte        20.0          NaN
4   Wednesday    Espresso        35.0          NaN
5   Wednesday       Latte        25.0          NaN
6    Thursday    Espresso        40.0          NaN
7    Thursday       Latte        30.0          NaN
8      Friday    Espresso        45.0          NaN
9      Friday       Latte        35.0          NaN
10   Saturday    Espresso        45.0          NaN
11   Saturday       Latte        35.0          NaN
12     Sunday    Espresso        45.0          NaN
13     Sunday       Latte        35.0          NaN

In [25]:
coffee.dropna(subset=['Units Sold'],inplace=True)

In [26]:
coffee

          Day Coffee Type  Units Sold  Unitss Sold
2     Tuesday    Espresso        30.0          NaN
3     Tuesday       Latte        20.0          NaN
4   Wednesday    Espresso        35.0          NaN
5   Wednesday       Latte        25.0          NaN
6    Thursday    Espresso        40.0          NaN
7    Thursday       Latte        30.0          NaN
8      Friday    Espresso        45.0          NaN
9      Friday       Latte        35.0          NaN
10   Saturday    Espresso        45.0          NaN
11   Saturday       Latte        35.0          NaN
12     Sunday    Espresso        45.0          NaN
13     Sunday       Latte        35.0          NaN

In [27]:
coffee.drop(columns='Unitss Sold')

          Day Coffee Type  Units Sold
2     Tuesday    Espresso        30.0
3     Tuesday       Latte        20.0
4   Wednesday    Espresso        35.0
5   Wednesday       Latte        25.0
6    Thursday    Espresso        40.0
7    Thursday       Latte        30.0
8      Friday    Espresso        45.0
9      Friday       Latte        35.0
10   Saturday    Espresso        45.0
11   Saturday       Latte        35.0
12     Sunday    Espresso        45.0
13     Sunday       Latte        35.0

In [28]:
# to find NaN row list coffee[coffee['UNits Sold'].isna()]
#not NaN row list  coffee[coffee['Units Sold].notna()]

Aggregating Data

In [29]:
bios = pd.read_csv('D:/bios.csv')

In [30]:
bios['born_city'].value_counts()

born_city
Budapest           1378
Moskva (Moscow)     883
Oslo                708
Stockholm           629
Praha (Prague)      600
                   ...
Kirovgrad             1
Pereiaslav            1
Podgornyy             1
Kudepsta              1
Furmanov              1
Name: count, Length: 22368, dtype: int64

In [33]:
bios[bios['born_country']=='USA']['born_region'].value_counts()

born_region
California              1634
New York                 990
Illinois                 585
Massachusetts            530
Pennsylvania             530
New Jersey               381
Texas                    368
Minnesota                365
Ohio                     328
Michigan                 319
Washington               240
Florida                  235
Wisconsin                209
Colorado                 207
Connecticut              156
Indiana                  150
Oregon                   132
Georgia                  129
Virginia                 121
Maryland                 117
District of Columbia     107
Iowa                     102
Hawaiʻi                   95
Kansas                    94
Oklahoma                  93
Louisiana                 92
Utah                      91
Missouri                  91
North Carolina            86
Arizona                   83
New Hampshire             83
Vermont                   68
Mississippi               66
Alabama                   64
Kentucky                  62
Tennessee                 62
Nebraska                  60
Rhode Island              56
Montana                   55
Maine                     50
South Carolina            50
Alaska                    45
Arkansas                  42
Idaho                     41
New Mexico                38
Nevada                    36
South Dakota              27
West Virginia             24
Delaware                  22
North Dakota              16
Wyoming                   14
Name: count, dtype: int64

In [35]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

Coffee Type
Espresso    240.0
Latte       180.0
Name: Units Sold, dtype: float64

In [36]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

Coffee Type
Espresso    40.0
Latte       30.0
Name: Units Sold, dtype: float64

In [37]:
coffee.groupby(['Coffee Type'])['Units Sold'].max()

Coffee Type
Espresso    45.0
Latte       35.0
Name: Units Sold, dtype: float64

In [48]:
coffee.drop(columns='Unitss Sold',inplace=True)

In [46]:
coffee.dropna(subset=['Units Sold'],inplace=True)

KeyError: ['Units Sold']

In [38]:
coffee.groupby(['Coffee Type']).agg({'Units Sold':'sum','price':'mean'})

KeyError: "Column(s) ['price'] do not exist"

In [49]:
coffee

          Day Coffee Type  new_price
2     Tuesday    Espresso       3.99
3     Tuesday       Latte       5.99
4   Wednesday    Espresso       3.99
5   Wednesday       Latte       5.99
6    Thursday    Espresso       3.99
7    Thursday       Latte       5.99
8      Friday    Espresso       3.99
9      Friday       Latte       5.99
10   Saturday    Espresso       3.99
11   Saturday       Latte       5.99
12     Sunday    Espresso       3.99
13     Sunday       Latte       5.99

In [50]:
coffee = pd.read_csv('D:/coffee.csv')

In [51]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [17]:
coffee['price'] = np.where(['Coffee Type']== 'Espresso',3.99,5.99)

In [18]:
coffee

          Day Coffee Type  Units Sold  price
0      Monday    Espresso          25   5.99
1      Monday       Latte          15   5.99
2     Tuesday    Espresso          30   5.99
3     Tuesday       Latte          20   5.99
4   Wednesday    Espresso          35   5.99
5   Wednesday       Latte          25   5.99
6    Thursday    Espresso          40   5.99
7    Thursday       Latte          30   5.99
8      Friday    Espresso          45   5.99
9      Friday       Latte          35   5.99
10   Saturday    Espresso          45   5.99
11   Saturday       Latte          35   5.99
12     Sunday    Espresso          45   5.99
13     Sunday       Latte          35   5.99

In [19]:
coffee['revenue']=coffee['Units Sold']*coffee['price']

In [55]:
coffee

          Day Coffee Type  Units Sold  price  revenue
0      Monday    Espresso          25   5.99   149.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   5.99   179.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   5.99   209.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   5.99   239.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   5.99   269.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   5.99   269.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   5.99   269.55
13     Sunday       Latte          35   5.99   209.65

In [56]:
coffee.groupby(['Coffee Type']).agg({'Units Sold':'sum','price':'mean'})

             Units Sold  price
Coffee Type
Espresso            265   5.99
Latte               195   5.99

In [59]:
coffee.groupby(['Coffee Type','Day']).agg({'Units Sold':'sum','price':'mean'})

                       Units Sold  price
Coffee Type Day
Espresso    Friday             45   5.99
            Monday             25   5.99
            Saturday           45   5.99
            Sunday             45   5.99
            Thursday           40   5.99
            Tuesday            30   5.99
            Wednesday          35   5.99
Latte       Friday             35   5.99
            Monday             15   5.99
            Saturday           35   5.99
            Sunday             35   5.99
            Thursday           30   5.99
            Tuesday            20   5.99
            Wednesday          25   5.99

In [60]:
pivot = coffee.pivot(columns='Coffee Type',index='Day',values='revenue')

In [61]:
pivot

Coffee Type  Espresso   Latte
Day
Friday         269.55  209.65
Monday         149.75   89.85
Saturday       269.55  209.65
Sunday         269.55  209.65
Thursday       239.60  179.70
Tuesday        179.70  119.80
Wednesday      209.65  149.75

In [62]:
pivot.loc['Monday']

Coffee Type
Espresso    149.75
Latte        89.85
Name: Monday, dtype: float64

In [63]:
pivot.loc['Monday','Latte']

np.float64(89.85000000000001)

In [64]:
pivot.sum(axis=1)

Day
Friday       479.2
Monday       239.6
Saturday     479.2
Sunday       479.2
Thursday     419.3
Tuesday      299.5
Wednesday    359.4
dtype: float64

In [66]:
bios.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [67]:
bios.groupby(bios['born_date'].dt.year)['name'].count()

AttributeError: Can only use .dt accessor with datetimelike values

In [7]:
bios_new.head(4)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,born_datetime
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,1886-12-12
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,1969-04-01
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,1898-08-13
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,1895-05-11

In [9]:
bios.head(3)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17

In [11]:
bios['born_date']= pd.to_datetime(bios['born_date'])
bios.groupby(bios['born_date'].dt.year)['name'].count()

born_date
1828.0      1
1831.0      2
1833.0      1
1836.0      1
1837.0      1
         ...
2005.0    163
2006.0     17
2007.0      3
2008.0      3
2009.0      1
Name: name, Length: 177, dtype: int64

In [ ]:
bios.groupby(bios['born_date'].dt.year)['name'].count().reset_index().sort_values('name') #to see higer order use ascending = false)

     born_date  name
0       1828.0     1
2       1833.0     1
3       1836.0     1
4       1837.0     1
6       1839.0     1
..         ...   ...
137     1970.0  2174
138     1971.0  2205
140     1973.0  2216
152     1985.0  2227
139     1972.0  2231

[177 rows x 2 columns]

In [14]:
bios['month_born']= bios['born_date'].dt.month
bios['year_born']=bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name',ascending=False)

      year_born  month_born  name
1437     1970.0         1.0   239
1461     1972.0         1.0   229
1497     1975.0         1.0   227
1629     1986.0         1.0   227
1617     1985.0         1.0   225
...         ...         ...   ...
1877     2006.0        12.0     1
1871     2006.0         3.0     1
20       1846.0         7.0     1
21       1846.0         8.0     1
22       1846.0         9.0     1

[1885 rows x 3 columns]

Advanced Functionality

In [ ]:
.shift() .rank() .rolling() .cumsum()

SyntaxError: invalid syntax (2877130052.py, line 1)

In [20]:
coffee.head()

         Day Coffee Type  Units Sold  price  revenue
0     Monday    Espresso          25   5.99   149.75
1     Monday       Latte          15   5.99    89.85
2    Tuesday    Espresso          30   5.99   179.70
3    Tuesday       Latte          20   5.99   119.80
4  Wednesday    Espresso          35   5.99   209.65

In [21]:
coffee['yesterday_revenue']=coffee['revenue'].shift(2)

In [22]:
coffee

          Day Coffee Type  Units Sold  price  revenue  yesterday_revenue
0      Monday    Espresso          25   5.99   149.75                NaN
1      Monday       Latte          15   5.99    89.85                NaN
2     Tuesday    Espresso          30   5.99   179.70             149.75
3     Tuesday       Latte          20   5.99   119.80              89.85
4   Wednesday    Espresso          35   5.99   209.65             179.70
5   Wednesday       Latte          25   5.99   149.75             119.80
6    Thursday    Espresso          40   5.99   239.60             209.65
7    Thursday       Latte          30   5.99   179.70             149.75
8      Friday    Espresso          45   5.99   269.55             239.60
9      Friday       Latte          35   5.99   209.65             179.70
10   Saturday    Espresso          45   5.99   269.55             269.55
11   Saturday       Latte          35   5.99   209.65             209.65
12     Sunday    Espresso          45   5.99   269.55             269.55
13     Sunday       Latte          35   5.99   209.65             209.65

In [23]:
coffee['pct_change']=(coffee['revenue']/coffee['yesterday_revenue'])*100

In [24]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change
0,Monday,Espresso,25,5.99,149.75,NaN,NaN
1,Monday,Latte,15,5.99,89.85,NaN,NaN
2,Tuesday,Espresso,30,5.99,179.70,149.75,120.000000
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333
4,Wednesday,Espresso,35,5.99,209.65,179.70,116.666667
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000
6,Thursday,Espresso,40,5.99,239.60,209.65,114.285714
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000
8,Friday,Espresso,45,5.99,269.55,239.60,112.500000
9,Friday,Latte,35,5.99,209.65,179.70,116.666667
10,Saturday,Espresso,45,5.99,269.55,269.55,100.000000
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000
12,Sunday,Espresso,45,5.99,269.55,269.55,100.000000
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000

In [25]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,12.0,1886.0
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,4.0,1969.0
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,8.0,1898.0
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,5.0,1895.0
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,4.0,1878.0

In [29]:

bios['height_rank'] = bios['height_cm'].rank(ascending=False)

In [32]:
bios.sort_values(['height_rank']).sample(10)

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
131760,134587,Giordano Benedetti,1989-05-22,Trento,Trento,ITA,Italy,189.0,67.0,NaN,5.0,1989.0,11668.0
128794,131359,UB Misech,1997-09-27,Koror,Koror,PLW,Palau,165.0,51.0,NaN,9.0,1997.0,91849.5
143047,146679,Paul Jacquot,1995-12-26,NaN,NaN,NaN,Switzerland,NaN,NaN,NaN,12.0,1995.0,NaN
23119,23293,Boris Nepokupnoy,1887-01-01,NaN,NaN,NaN,Russian Federation,NaN,NaN,NaN,1.0,1887.0,NaN
98552,99348,Hiroaki Yamakage,1974-10-30,Shihoro,Hokkaido,JPN,Japan,178.0,83.0,NaN,10.0,1974.0,46966.0
24056,24243,Valdez,1943-02-10,Araraquara,São Paulo,BRA,Brazil,NaN,NaN,NaN,2.0,1943.0,NaN
51648,52007,Claudio Zulianello,1965-05-29,NaN,NaN,NaN,Argentina,198.0,91.0,NaN,5.0,1965.0,2110.5
80003,80654,Franca Bianconi,1962-03-03,Milano,Milano,ITA,Italy,NaN,NaN,NaN,3.0,1962.0,NaN
103098,104067,Jamie Hunt,1979-06-21,Wellington,Wellington,NZL,New Zealand,175.0,71.0,NaN,6.0,1979.0,58380.5
77260,77851,Carlette Guidry-White,1968-09-04,Houston,Texas,USA,United States,168.0,50.0,NaN,9.0,1968.0,83975.0

In [34]:
bios.sort_values(['height_rank']).sample(10)[['name','height_rank']]

                       name  height_rank
69941       Heinrich Rehder          NaN
50619            Lynn Burke      66080.0
18827     Wolfgang Baumgart      18122.0
4705    Hennie Quentemeijer          NaN
13436    Marcello Bartalini       5736.0
104472        Daniel Bailey      43071.5
97882       Rostislav Vlach      34234.5
135296  Amélie Klopfenstein          NaN
129189       Frida Tegstedt      38677.0
111435         Ysis Barreto     102145.5

In [35]:
coffee['cumulative_revenue']=coffee['revenue'].cumsum()

In [36]:
coffee

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue
0,Monday,Espresso,25,5.99,149.75,NaN,NaN,149.75
1,Monday,Latte,15,5.99,89.85,NaN,NaN,239.60
2,Tuesday,Espresso,30,5.99,179.70,149.75,120.000000,419.30
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,539.10
4,Wednesday,Espresso,35,5.99,209.65,179.70,116.666667,748.75
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,898.50
6,Thursday,Espresso,40,5.99,239.60,209.65,114.285714,1138.10
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1317.80
8,Friday,Espresso,45,5.99,269.55,239.60,112.500000,1587.35
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1797.00
10,Saturday,Espresso,45,5.99,269.55,269.55,100.000000,2066.55
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,2276.20
12,Sunday,Espresso,45,5.99,269.55,269.55,100.000000,2545.75
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2755.40

In [39]:
latte = coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3_day']= latte['Units Sold'].rolling(3).sum()

In [40]:
latte

,Day,Coffee Type,Units Sold,price,revenue,yesterday_revenue,pct_change,cumulative_revenue,3_day
1,Monday,Latte,15,5.99,89.85,NaN,NaN,239.6,NaN
3,Tuesday,Latte,20,5.99,119.80,89.85,133.333333,539.1,NaN
5,Wednesday,Latte,25,5.99,149.75,119.80,125.000000,898.5,60.0
7,Thursday,Latte,30,5.99,179.70,149.75,120.000000,1317.8,75.0
9,Friday,Latte,35,5.99,209.65,179.70,116.666667,1797.0,90.0
11,Saturday,Latte,35,5.99,209.65,209.65,100.000000,2276.2,100.0
13,Sunday,Latte,35,5.99,209.65,209.65,100.000000,2755.4,105.0

New Functionality

In [47]:
filtered_bios=bios[(bios['born_region'] == 'New Hampshire') | (bios['born_city'] == 'San Francisco')]
filtered_bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,month_born,year_born,height_rank
6128,6155,Raúl García-Ordóñez,1924-09-15,Littleton,New Hampshire,USA,Cuba,188.0,NaN,2013-05-03,9.0,1924.0,13590.5
7290,7329,Jim Walsh,1930-08-29,San Francisco,California,USA,United States,193.0,86.0,1976-03-04,8.0,1930.0,5736.0
8619,8666,George Finnegan,1881-09-28,San Francisco,California,USA,United States,NaN,NaN,1913-02-28,9.0,1881.0,NaN
8639,8686,Frank Haller,1883-01-06,San Francisco,California,USA,United States,NaN,NaN,1939-04-30,1.0,1883.0,NaN
10981,11038,DeAnne Hemmens,1964-07-02,San Francisco,California,USA,United States,NaN,NaN,NaN,7.0,1964.0,NaN